version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_sentinel
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/static
    depends_on:
      - interfaceserver
  interfaceserver:
    build: 
      context: .
      args:
        user_id: 1000
    command: /entry/entrypoint-interface.sh
    user: sentinel
    working_dir: /sentinel
    expose:
      - "8000"
    env_file:
      - docker.env
    depends_on:
      - database
      - redis
    volumes:
      - static:/sentinel/static
  workerserver:
    build: 
      context: .
      args:
        user_id: 1000
    user: sentinel
    working_dir: /sentinel
    command: /entry/entrypoint-worker.sh
    env_file:
      - docker.env
    depends_on:
      - database
      - redis
  database:
    image: postgres:9.5
  redis:
    image: redis:3.0-alpine
volumes:
   static:
