version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/sentinel.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    depends_on:
      - interfaceserver
  interfaceserver:
    build: 
      context: .
      args:
        user_id: 1000
    image: sentinel:${ID:-latest}
    command: sh /entry/entrypoint-interface.sh
    expose:
      - "8000"
    env_file:
      - config/docker.env
    depends_on:
      - database
      - redis
    volumes:
      - static:/sentinel/static
  workerserver:
    image: sentinel:${ID:-latest}
    command: sh /entry/entrypoint-worker.sh
    env_file:
      - config/docker.env
    depends_on:
      - database
      - redis
  database:
    image: postgres:9.5
  redis:
    image: redis:3.0-alpine
volumes:
   static:
