version: '3'
services:
  nginx:
    ports:
      - "80:80"
  interfaceserver:
    env_file:
      - config/local.env
  workerserver:
    env_file:
      - config/local.env
  database:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: