version: '3.4'
services:
  nginx:
    container_name: sentinel-nginx
    env_file:
      - config/production.env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/production.conf:/config/production.conf
      - /docker-volumes/etc/letsencrypt/live/${SENTINEL_HOST}/fullchain.pem:/certs/cert.pem
      - /docker-volumes/etc/letsencrypt/live/${SENTINEL_HOST}/privkey.pem:/certs/key.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
      - nginx_logs:/logs
    command: /bin/bash -c "envsubst '$$DJANGO_HOSTNAME' < /config/production.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  interfaceserver:
    env_file:
      - config/production.env
  workerserver:
    env_file:
      - config/production.env
  database:
    env_file:
      - config/production.env
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  nginx_logs:
